package Chapter3.Constructors;

public class Cat {
  String name;
  String color;

  //    It is not called the default constructor.
  //    the default constructor is only generated by compiler.
  private Cat() {
    this("Bao","HI");
  }

  Cat(String name) {
    this();
    this.name = name;
  }

  Cat(String name, String color) {

    this.name = name;
    this.color = color;
  }

  void a() {
  }
}
